defaults: &common-config
  working_directory: ~/release-it-mono
  docker:
    - image: circleci/node:10

restore_cache_config: &restore-cache-config
  name: Restore Yarn package cache
  keys:
    - yarn-packages-{{ checksum "yarn.lock" }}

install_deps: &install-deps
  name: Install dependencies
  command: yarn install --frozen-lockfile

save_cache_config: &save-cache-config
  name: Save Yarn package cache
  key: yarn-packages-{{ checksum "yarn.lock" }}
  paths:
    - node_modules

version: 2
jobs:
  install:
    <<: *common-config
    steps:
      - checkout
      - restore_cache: *restore-cache-config
      - run: *install-deps
      - save_cache: *save-cache-config
      - persist_to_workspace:
          root: ~/release-it-mono
          paths:
            - .
  release-it:
    <<: *common-config
    steps:
      - add_ssh_keys:
          fingerprints:
            - "32:8f:6b:7d:aa:3b:62:f4:8a:ba:92:1e:e5:17:a4:58"
            - "27:ce:dc:e5:57:b9:f2:21:c3:7d:ae:6c:20:46:4f:e6"
            - "a0:54:f3:a5:60:f0:e9:80:34:68:b0:05:95:5e:ad:9e"
      - attach_workspace:
          at: ~/release-it-mono
      - run:
          name: Build
          command: |
            INCREMENT=patch
            [[ $CIRCLE_BRANCH = rc-* ]] && INCREMENT=major
            [[ $CIRCLE_BRANCH = hotfix-* ]] && INCREMENT=minor
            mkdir -p ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
            git config --global user.name "release-it-bot"
            yarn release -- $INCREMENT --ci
      - persist_to_workspace:
          root: ~/release-it-mono
          paths:
            - .

workflows:
  version: 2
  build_deploy_test:
    jobs:
      - install:
          filters:
            branches:
              only: 
                - master
                - /rc-.*/
                - /hotfix-.*/
      - release-it:
          requires:
            - install
