version: 2.1
orbs:
  node: circleci/node@10.10.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn release -- minor --ci
workflows:
    build-and-test:
      jobs:
        - build-and-test